# install:
#   - composer install
#   - composer prepare-tests

# script:
#   - composer phpunit
#   - composer behat || composer behat-rerun

# jobs:
#   include:
#     - stage: sniff
#       script:
#         - composer lint
#         - composer phpcs
#       env: BUILD=sniff
#     - stage: test
#       php: 7.2
#       env: WP_VERSION=latest
#     - stage: test
#       php: 7.2
#       env: WP_VERSION=3.7.11
#     - stage: test
#       php: 7.2
#       env: WP_VERSION=trunk
