language: php

sudo: false

php:
  - '7.0'

before_script:
  - composer self-update --no-interaction
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=ruleset.xml
